### ISSUE TITLE
Adapter crashes on attempt to overwrite a file

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Excel_Toolkit#63]
#### Description:

As in the title, when trying to overwrite an Excel file using Excel_Adapter I run into the following exception in `PushObjects` method:
![image](https://github.com/BHoM/Excel_Toolkit/assets/26874773/395d4b43-6b9b-401d-bf2f-ce327266cc81)

Assigning four of us as it might be something we can solve using our collective knowledge about the bug.

**Comment by travispotterBH** [comment]
Hey Pawel, thanks for bringing this to our attention. Fraser, Tom, and I took a look at this over the past few days, so very top of mind!

Try a few things first: 
- Delete from your .nuget folder all versions of System.IO.Packaging (C:\Users\{Your Username Here}\.nuget\packages\system.io.packaging)  This is mostly an extra precaution
- Delete from your Assemblies folder the single DLL of System.IO.Packaging (C:\ProgramData\BHoM\Assemblies)

Reinstall the Beta (which hopefully has yesterday's (March 18, 2024) commit (9c27a1d1bfc9b4516c7fb5ef0da59de31cbb6044) and then try again.

I believe that there is an issue where since there is already a version of System.IO.Packaging (which is used by different toolkit's dependencies and different versions at that!) it is not being overwritten in Assemblies. 
Please let me know what happens once you've given that a try.

**Comment by pawelbaran** [comment]
Thanks @travispotterBH. I followed the instruction, unfortunately still same error 😢

**Comment by travispotterBH** [comment]
Interesting, try building off excel toolkit develop branch. 

There {may} be something off about the installer. In my test yesterday of the develop branch it ran through this exact test case without issue.

**Comment by pawelbaran** [comment]
I did it at some point yesterday to debug, same exception in every scenario... Are you sure you did test against overwriting a file? I only get the exception on attempt to overwrite, creating a new one is perfectly fine.

**Comment by travispotterBH** [comment]
After Discussions with DevOps the appropriate action for now appears to be to downgrade the dependency version, and resolve the conflict in PowerPoint Toolkit.
