### ISSUE TITLE
Pull fails when Excel file contains formulas

### ISSUE THREAD

**Issue by bjoernsteinhagen** [BHoM/Excel_Toolkit#69]
#### Description:

- I read in an Excel file, which previously worked fine. The file has very simple formulas.
- With the latest version of BHoM (7.2.0.240424), the pull fails.
- I copied all text within the Excel file and pasted the data again just as values (removing formulas) and the pull then worked.

#### Steps to reproduce:

- Create an Excel file where some rows use formulas
- Try and read in the file in GH using BHoM pull (and Excel adapter)

#### Expected behaviour:

- The adapter reads in the values which are as a result of the functions, not producing an error.

**Comment by HugoVanLooveren** [comment]
I guess related to this issue is the fact that importing Excel content results in Goo types for numbers. 
![image](https://github.com/BHoM/Excel_Toolkit/assets/123378333/47bfa210-2529-4418-b065-01ead01ce157)

In BHoM version 7.0.1.1 it works:
![image](https://github.com/BHoM/Excel_Toolkit/assets/123378333/ba869890-8af1-4e2c-8977-61dd67ae371e)

To reproduce you need an Excel with a column filled with numbers. You can also use the one attached: 
[Book2.xlsx](https://github.com/BHoM/Excel_Toolkit/files/15108279/Book2.xlsx)
(Could not attach a .gh file, so that should be made by yourself)
